### ISSUE TITLE
Singularity Hub builders fail to build Arch Linux containers

### ISSUE THREAD

**Issue by rprechelt** [singularityhub/builders#9]
I'm not sure if this is the correct place to open this issue (please redirect me if it isn't) but the builders on singularity-hub.org cannot build any Arch Linux based images because they don't have the necessary tools installed, namely `pacstrap` and `arch-install-scripts`

## Steps to reproduce
Create a `Singularity` containing only

``
Bootstrap: arch
``

and commit it to a `singularity-hub.org` connected Github repo to trigger a build. The `singularity-hub.org` builders will fail with 

``
ERROR Return Code 1: ("ERROR: `pacstrap' is not in PATH. You can install it with `pacman -S arch-install-scripts'.
ABORT: Aborting with RETVAL=1
",)
``

See the full log from an Arch container build here: https://www.singularity-hub.org/containers/2890/log

**Comment by vsoch** [comment]
We will need to update the builders for the packages, ping @cclerget for the next secure build container!

**Comment by vsoch** [comment]
For the future, here is the repo that normally issues are posted for! https://github.com/singularityhub/singularityhub.github.io/issues/132 It's the same one with the help / docs.

**Comment by rprechelt** [comment]
Great! Thanks! There were so many repo's under `singularityhub` and I was a little unclear on which repo would be most suited to this issue.
